name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint || true
      - run: pnpm run build

  api:
    runs-on: ubuntu-latest
    if: hashFiles('api/composer.json') != ''
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: php -v
      - run: php -m
      - run: php artisan --version || true
