name: e2e

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      E2E_BASE_URL: https://web.sketchupplaystore.com
      NEXT_PUBLIC_API_BASE: https://api.sketchupplaystore.com

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install deps
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Adjust if your e2e command differs
      - name: Run e2e
        run: pnpm run test:e2e || true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report
          if-no-files-found: warn