name: web CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: |
            web/pnpm-lock.yaml

      - name: Install
        run: pnpm install --frozen-lockfile=false

      # Lint (loose) – warnings allowed, errors fail
      - name: Lint
        run: pnpm run lint:loose

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
